services:
  db:
    image: postgres:18.1-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    networks:
      - app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  app:
    container_name: "linkeer-app"
    build:
      context: .
    env_file:
      - .env
    command: 'sh -c "
      sleep 10 && 
      python3 manage.py migrate && 
      python3 manage.py setup_link_categories &&
      python3 manage.py setup_tenants &&
      python3 manage.py createsuperuser --no-input --username=${ADMIN_USERNAME} --email=${ADMIN_EMAIL} || true &&
      python3 manage.py runserver 0.0.0.0:8000
    "'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - app
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin/pgpass:/pgadmin4/pgpass:ro
    ports:
      - "5050:80"
    depends_on:
      - db

networks:
  app:
volumes:
  postgres_data:
  pgadmin_data:
