# Generated by Django 5.2.10 on 2026-01-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
