# Generated by Django 6.0.1 on 2026-01-18 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdomain',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
