# Generated by Django 6.0.1 on 2026-01-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenantdomain_created_on'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(('schema_name', 'public')), fields=('schema_name',), name='unique_public_schema'),
        ),
    ]
