# Generated by Django 6.0.1 on 2026-01-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_unique_public_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
