# Generated by Django 6.0.1 on 2026-01-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#021b33', max_length=40),
            preserve_default=False,
        ),
    ]
