# Generated by Django 6.0.1 on 2026-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_primary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#A987A5', max_length=40),
        ),
    ]
