# Generated by Django 6.0.1 on 2026-01-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_tenant_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='branding_icon',
            field=models.FileField(null=True, upload_to='fazueli_docs'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(max_length=40),
        ),
    ]
