# Generated by Django 6.0.1 on 2026-01-26 18:32

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_branding_icon_alter_tenant_primary_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='is_primary',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='branding_icon',
            field=models.ImageField(blank=True, null=True, upload_to=tenants.models.tenant_branding_upload_to),
        ),
    ]
