# Generated by Django 5.2.10 on 2026-01-26 18:40

import tenants.models
import tenants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_remove_tenant_is_primary_alter_tenant_branding_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='branding_icon',
            field=models.ImageField(null=True, upload_to=tenants.models.tenant_branding_upload_to, validators=[tenants.validators.validate_file_extension, tenants.validators.validate_file_size]),
        ),
    ]
