# Generated by Django 5.2.10 on 2026-01-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_alter_tenant_branding_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
