# Generated by Django 5.2.10 on 2026-01-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdomain',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
