# Generated by Django 5.2.11 on 2026-02-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_alter_tenantdomain_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdomain',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
