# Generated by Django 5.2.11 on 2026-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_tenantdomain_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
