# Generated by Django 6.0.1 on 2026-01-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_order_alter_link_domain'),
        ('tenants', '0005_tenantdomain_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='order',
        ),
        migrations.AddField(
            model_name='link',
            name='exibition_order',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('domain', 'exibition_order'), name='unique_exibition_order_per_domain'),
        ),
    ]
