# Generated by Django 5.2.10 on 2026-01-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_tenant_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
