# Generated by Django 6.0.1 on 2026-01-19 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_remove_link_order_link_exibition_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='exibition_order',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
