# Generated by Django 5.2.10 on 2026-01-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_link_description_alter_link_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='emphasis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
