# Generated by Django 5.2.10 on 2026-02-01 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_linkclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkclick',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
