# Generated by Django 5.2.11 on 2026-02-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_alter_linkclick_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
