# Generated by Django 5.2.11 on 2026-02-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_alter_link_description'),
        ('tenants', '0016_alter_tenant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('domain', 'name'), name='unique_link_name_per_domain'),
        ),
    ]
